/*
 * ============================================================
 * FILE: storage.test.mjs
 * PURPOSE: Exercises Storage Forensics's domain behavior, validation, persistence, reporting, and safety boundaries with the Node.js test runner.
 * ============================================================
 */

import assert from "node:assert/strict";import test from "node:test";import { mkdtemp,readFile,rm,writeFile } from "node:fs/promises";import { tmpdir } from "node:os";import { join } from "node:path";import { aggregateScan,assertSafeScope,compareSnapshots,createSnapshot,scanFolder } from "../src/analyze.mjs";import { createSyntheticFixture } from "../src/fixtures.mjs";import { reportHtml,writeReport } from "../src/report.mjs";
async function fixture(){const root=await mkdtemp(join(tmpdir(),'storage-forensics-'));await createSyntheticFixture(root);return root}test('aggregates synthetic file metadata into folder and type distributions',()=>{const scan=aggregateScan('/safe',[{path:'/safe/a.txt',relativePath:'docs/a.txt',name:'a.txt',extension:'.txt',size:10,modifiedAt:1},{path:'/safe/image.bin',relativePath:'media/image.bin',name:'image.bin',extension:'.bin',size:90,modifiedAt:1}],[],[],{oldDays:1,scannedEntries:2});assert.equal(scan.summary.totalBytes,100);assert.equal(scan.folderSizes[0].folder,'media');assert.equal(scan.fileTypes.find(item=>item.extension==='.txt').count,1)});test('finds same-content duplicate groups by streaming candidate hashes',async()=>{const root=await fixture();try{const scan=await scanFolder(root);assert.equal(scan.duplicates.length,1);assert.equal(scan.duplicates[0].files.length,2);assert.equal(scan.duplicates[0].wastedBytes,scan.duplicates[0].size)}finally{await rm(root,{recursive:true,force:true})}});test('excludes configured paths and refuses protected system scopes',async()=>{const root=await fixture();try{const scan=await scanFolder(root,{exclusions:['media']});assert.equal(scan.files.some(file=>file.relativePath.startsWith('media')),false);assert.throws(()=>assertSafeScope('/proc'),/protected system path/)}finally{await rm(root,{recursive:true,force:true})}});test('creates comparable snapshots and reports growth changes',()=>{const first=createSnapshot(aggregateScan('/safe',[{relativePath:'a.txt',size:10,modifiedAt:1}],[],[],{}));const second=createSnapshot(aggregateScan('/safe',[{relativePath:'a.txt',size:15,modifiedAt:2},{relativePath:'b.txt',size:5,modifiedAt:2}],[],[],{}));const result=compareSnapshots(first,second);assert.equal(result.bytesDelta,10);assert.equal(result.added,1);assert.equal(result.changed,1)});test('writes an explicitly read-only report with distributions and duplicate boundaries',async()=>{const root=await fixture(),out=await mkdtemp(join(tmpdir(),'storage-forensics-report-'));try{const scan=await scanFolder(root),outputs=await writeReport(scan,out),html=await readFile(outputs.html,'utf8');assert.match(html,/Read-only local storage inventory/);assert.match(html,/Folder-size map/);assert.match(html,/Duplicate groups/);assert.match(reportHtml(scan),/does not change, delete, move, or upload/)}finally{await rm(root,{recursive:true,force:true});await rm(out,{recursive:true,force:true})}});
