/*
 * ============================================================
 * FILE: analyze.mjs
 * PURPOSE: Derives Storage Forensics's summaries and findings from normalized local metadata.
 * ============================================================
 */

import { createReadStream } from "node:fs";import { opendir,stat,statfs } from "node:fs/promises";import { createHash } from "node:crypto";import { basename,relative,resolve,sep } from "node:path";
const DEFAULT_EXCLUSIONS=new Set(['.git','node_modules','.cache','System Volume Information','$RECYCLE.BIN']);const SYSTEM_PREFIXES=['/proc','/sys','/dev','/etc','/boot','/usr','/bin','/sbin','/var/lib','/windows','/program files'];const MAX_FILES=200000;
const number=value=>Number.isFinite(value)?value:0;const safeTime=value=>Number.isFinite(value)?value:0;export const formatBytes=bytes=>{const value=number(bytes),units=['B','KB','MB','GB','TB'];let unit=0,size=value;while(size>=1024&&unit<units.length-1){size/=1024;unit+=1}return `${Number(size.toPrecision(4))} ${units[unit]}`};
export function assertSafeScope(root){const path=resolve(root),lower=path.toLowerCase();if(path===sep||SYSTEM_PREFIXES.some(prefix=>lower===prefix||lower.startsWith(`${prefix}${sep}`)))throw new Error('Refusing to scan a protected system path. Select a specific user folder or mounted data folder instead.');return path}
function excluded(path,root,exclusions){const parts=relative(root,path).split(sep);return parts.some(part=>exclusions.has(part))}
async function hashFile(path){const hash=createHash('sha256');for await(const chunk of createReadStream(path,{highWaterMark:1024*1024}))hash.update(chunk);return hash.digest('hex')}
export async function scanFolder(root,{exclusions=[],oldDays=365,limit=MAX_FILES,onProgress=()=>{}}={}){const target=assertSafeScope(root),excludedNames=new Set([...DEFAULT_EXCLUSIONS,...exclusions].filter(Boolean));const files=[],skipped=[];let scannedEntries=0;const stack=[target];while(stack.length){const directory=stack.pop();let handle;try{handle=await opendir(directory)}catch(error){skipped.push({path:directory,reason:error.code??'unreadable'});continue}for await(const entry of handle){const path=resolve(directory,entry.name);scannedEntries+=1;if(scannedEntries%250===0)onProgress({scannedEntries,queuedDirectories:stack.length,files:files.length});if(excluded(path,target,excludedNames)){skipped.push({path,reason:'excluded'});continue}if(entry.isSymbolicLink()){skipped.push({path,reason:'symlink-not-followed'});continue}if(entry.isDirectory()){stack.push(path);continue}if(!entry.isFile())continue;try{const info=await stat(path);if(files.length>=limit)throw new Error(`File limit of ${limit} reached; narrow scope or use exclusions.`);const extension=(entry.name.lastIndexOf('.')>0?entry.name.slice(entry.name.lastIndexOf('.')).toLowerCase():'[no extension]');files.push({path,relativePath:relative(target,path)||basename(path),name:entry.name,extension,size:number(info.size),modifiedAt:safeTime(info.mtimeMs)});}catch(error){if(error.message.includes('File limit'))throw error;skipped.push({path,reason:error.code??'stat-failed'})}}}onProgress({scannedEntries,queuedDirectories:0,files:files.length,complete:true});const sizeGroups=new Map;for(const file of files){if(file.size===0)continue;const group=sizeGroups.get(file.size)??[];group.push(file);sizeGroups.set(file.size,group)}const duplicates=[];for(const candidates of sizeGroups.values()){if(candidates.length<2)continue;const byHash=new Map;for(const file of candidates){try{const hash=await hashFile(file.path);const group=byHash.get(hash)??[];group.push(file);byHash.set(hash,group)}catch(error){skipped.push({path:file.path,reason:error.code??'hash-failed'})}}for(const [hash,group] of byHash)if(group.length>1)duplicates.push({hash,size:group[0].size,files:group,wastedBytes:group[0].size*(group.length-1)})}return aggregateScan(target,files,duplicates,skipped,{oldDays,exclusions:[...excludedNames],scannedEntries})}
export function aggregateScan(root,files,duplicates=[],skipped=[],{oldDays=365,exclusions=[],scannedEntries=files.length}={}){const now=Date.now(),cutoff=now-Number(oldDays)*86400000,typeMap=new Map,folderMap=new Map;for(const file of files){const type=typeMap.get(file.extension)??{extension:file.extension,count:0,bytes:0};type.count+=1;type.bytes+=file.size;typeMap.set(file.extension,type);const first=file.relativePath.split(sep)[0]||'[root]';const folder=folderMap.get(first)??{folder:first,count:0,bytes:0};folder.count+=1;folder.bytes+=file.size;folderMap.set(first,folder)}const totalBytes=files.reduce((sum,file)=>sum+file.size,0);return{schemaVersion:'storage-forensics/v1',createdAt:new Date().toISOString(),root,summary:{files:files.length,totalBytes,duplicateGroups:duplicates.length,reclaimableDuplicateBytes:duplicates.reduce((sum,group)=>sum+group.wastedBytes,0),oldFiles:files.filter(file=>file.modifiedAt<cutoff).length,skipped:skipped.length,scannedEntries},files:[...files],largestFiles:[...files].sort((a,b)=>b.size-a.size).slice(0,30),fileTypes:[...typeMap.values()].sort((a,b)=>b.bytes-a.bytes),folderSizes:[...folderMap.values()].sort((a,b)=>b.bytes-a.bytes),duplicates,oldFiles:files.filter(file=>file.modifiedAt<cutoff).sort((a,b)=>a.modifiedAt-b.modifiedAt).slice(0,100),skipped,options:{oldDays,exclusions}}}
export async function capacityFor(path){try{const info=await statfs(path),block=Number(info.bsize),total=Number(info.blocks)*block,free=Number(info.bavail)*block;return{totalBytes:total,freeBytes:free,usedBytes:Math.max(0,total-free)}}catch{return{totalBytes:null,freeBytes:null,usedBytes:null}}}
export function createSnapshot(scan){return{schemaVersion:'storage-forensics-snapshot/v1',createdAt:new Date().toISOString(),root:scan.root,summary:scan.summary,fileIndex:Object.fromEntries(scan.files.map(file=>[file.relativePath,{size:file.size,modifiedAt:file.modifiedAt}]))}}
export function compareSnapshots(previous,current){if(previous?.schemaVersion!=='storage-forensics-snapshot/v1'||current?.schemaVersion!=='storage-forensics-snapshot/v1')throw new Error('Both snapshots must use the Storage Forensics snapshot schema.');const oldFiles=previous.fileIndex??{},newFiles=current.fileIndex??{};let added=0,removed=0,changed=0,addedBytes=0,removedBytes=0;for(const[path,file]of Object.entries(newFiles)){if(!(path in oldFiles)){added+=1;addedBytes+=number(file.size)}else if(number(file.size)!==number(oldFiles[path].size)||number(file.modifiedAt)!==number(oldFiles[path].modifiedAt))changed+=1}for(const[path,file]of Object.entries(oldFiles))if(!(path in newFiles)){removed+=1;removedBytes+=number(file.size)}return{previousAt:previous.createdAt,currentAt:current.createdAt,bytesDelta:number(current.summary?.totalBytes)-number(previous.summary?.totalBytes),filesDelta:number(current.summary?.files)-number(previous.summary?.files),added,removed,changed,addedBytes,removedBytes}}
